
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/workflowdbv2?TimeZone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.hikari.maximum-pool-size=5

spring.jackson.time-zone=Asia/Kolkata
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
logging.level.org.springframework.jdbc.core.JdbcTemplate=INFO
logging.level.com.example.workflow=DEBUG

# Engine (Java scheduler)
engine.enabled=true
engine.tick-ms=500
engine.step-sleep-ms=2000
